backend:
  name: git-gateway
  branch: main  # Replace "main" with your default branch if it's different

media_folder: "static/images"  # Optional: Folder for media uploads
public_folder: "/images"  # URL path for accessing media files

collections:
  - name: "videos"
    label: "Videos"
    folder: "/"  # Path to your `videos.json` file
    create: true  # Allow adding new items
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "url", label: "URL", widget: "string" }
      - { name: "description", label: "Description", widget: "text" }
